CREATE table "USERPURCHASEDETAILS" (
    "USERPURCHASEDETAILSID" NUMBER NOT NULL,
    "USERID"                NUMBER NOT NULL,
    "PRODUCTID"             NUMBER NOT NULL,
    "UNIQUEPRODUCTNUMBER"   NUMBER NOT NULL,
    "USERPURCHASEDATE"      DATE NOT NULL,
    constraint  "USERPURCHASEDETAILS_PK" primary key ("USERPURCHASEDETAILSID")
);