CREATE table "CUSTOMERPURCHASEDETAILS" (
    "CUSTOMERPURCHASEID" NUMBER NOT NULL,
    "CUSTOMEREMAIL"                VARCHAR2(50) NOT NULL,
    "PRODUCTID"             	NUMBER NOT NULL,
    "UNIQUEPRODUCTNUMBER"   NUMBER NOT NULL,
    "CUSTOMERPURCHASEDATE"      DATE NOT NULL,
    constraint  "CUSTOMERPURCHASEDETAILS_PK" primary key ("CUSTOMERPURCHASEID")
);

create sequence "PURCHASE_INCREMENT"
start with 1
increment by 1
nocache
nocycle
noorder;